microservice-a:
  IntValue: 44
  BoolValue: true
  UrlValue: https://an/uri
  Dictionnary:
    key1: 5
    key2: 5
    key3: 6
  ComplexTypeValue:
    PropertyA: 4
    PropertyB: true
    PropertyC: a value to send

microservice-b:
  IntValue: 44
  BoolValue: true
  UrlValue: https://an/uri
  Dictionnary:
    key1: 5
    key2: 5
    key3: 6
  ComplexTypeValue:
    PropertyA: 4
    PropertyB: true
    PropertyC: a value to send