microservice:
  IntValue: 10
  BoolValue: true
  UrlValue: https://an/uri
  Dictionnary:
    key1: 1
    key2: 2
    key3: 3
  ComplexTypeValue:
    PropertyA: 1
    PropertyB: true
    PropertyC: text