microservice-a:
  IntValue: 88
  BoolValue: true
  UrlValue: https://an/uri
  Dictionnary:
    key1: 5
    key2: 5
    key3: 6
  ComplexTypeValue:
    PropertyA: 4
    PropertyB: true
    PropertyC: a value to send

microservice-b:
  IntValue: 100
  BoolValue: false
  UrlValue: https://another/uri
  Dictionnary:
    key1: 7
    key2: 8
    key3: 9
  ComplexTypeValue:
    PropertyA: 10
    PropertyB: false
    PropertyC: a new text