microservice:
  IntValue: 42
  BoolValue: true
  UrlValue: https://an/uri
  Dictionnary:
    key1: 5
    key2: 4
    key3: 3
  ComplexTypeValue:
    PropertyA: 2
    PropertyB: false
    PropertyC: text-text